# Generated by Django 6.0.2 on 2026-03-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
