# Generated by Django 6.0.2 on 2026-03-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_event_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
