# Generated by Django 6.0.2 on 2026-03-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_event_meeting_link_event_tags_event_view_count'),
    ]

    operations = [
    ]
